package com.qrhry.app.domain

enum class UserMessageKey {
    GENERIC_ERROR,
    GAME_TITLE_REQUIRED,
    MINIMUM_STATIONS_REQUIRED,
    STATION_TITLE_REQUIRED,
    TASK_ORDER_INVALID,
    TASK_ID_INVALID,
    QUESTION_REQUIRED,
    MINIMUM_OPTIONS_REQUIRED,
    OPTION_ORDER_INVALID,
    OPTION_TEXT_REQUIRED,
    EXACTLY_ONE_CORRECT_OPTION_REQUIRED,
    OPTION_ID_INVALID,
    GAME_UNAVAILABLE,
    GAME_HAS_NO_STATIONS,
    STATION_UNAVAILABLE,
    SESSION_UNAVAILABLE,
    SESSION_COMPLETED,
    TASK_UNAVAILABLE,
    TASK_NOT_CURRENT,
    TASK_ALREADY_COMPLETED,
    ANSWER_UNAVAILABLE,
    SELECT_ANSWER_FIRST,
    TASK_EDIT_ACTIVE_SESSION,
    TASK_DELETE_HAS_ATTEMPTS,
    MEDIA_GAME_ID_INVALID,
    MEDIA_TYPE_UNKNOWN,
    MEDIA_TYPE_UNSUPPORTED,
    MEDIA_OPEN_FAILED,
    MEDIA_EMPTY,
    MEDIA_STORE_FAILED,
    MEDIA_PATH_INVALID,
    GAME_SAVE_FAILED,
    STATION_SAVE_FAILED,
    ANSWER_SELECT_FAILED,
    ANSWER_SUBMIT_FAILED,
    GAMES_LOAD_FAILED,
    SESSION_START_FAILED,
    SCANNER_LOOKUP_FAILED
}

class UserMessageException(val messageKey: UserMessageKey) : RuntimeException()

fun Throwable.messageKeyOr(fallback: UserMessageKey): UserMessageKey =
    (this as? UserMessageException)?.messageKey ?: fallback